/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function nextOccurrence(expression: string, after: string, options?: NextOccurrenceOptions | undefined | null): string

export interface NextOccurrenceOptions {
  /** An IANA timezone such as `America/New_York`. Omit for UTC evaluation. */
  timezone?: string
  /** `wallClockOnce` (default) or `wallClockTwice`. */
  dstPolicy?: string
}
